/**
* dynmonitor API generated from dynmonitor.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* DynmonitorApiImpl.h
*
*
*/

#pragma once


#include <memory>
#include <map>
#include <mutex>
#include "../Dynmonitor.h"

#include "DataplaneJsonObject.h"
#include "DataplaneMetricsJsonObject.h"
#include "DataplaneMetricsCountersJsonObject.h"
#include "DataplaneMetricsCountersLablesJsonObject.h"
#include "DynmonitorJsonObject.h"
#include "MetricsJsonObject.h"
#include "MetricsEntryJsonObject.h"
#include "MetricsEntryLablesJsonObject.h"
#include <vector>

namespace polycube {
namespace service {
namespace api {

using namespace polycube::service::model;

namespace DynmonitorApiImpl {
  void create_dynmonitor_by_id(const std::string &name, const DynmonitorJsonObject &value);
  void create_dynmonitor_dataplane_by_id(const std::string &name, const DataplaneJsonObject &value);
  void create_dynmonitor_dataplane_metrics_by_id(const std::string &name, const DataplaneMetricsJsonObject &value);
  void create_dynmonitor_dataplane_metrics_counters_by_id(const std::string &name, const std::string &countersName, const DataplaneMetricsCountersJsonObject &value);
  void create_dynmonitor_dataplane_metrics_counters_lables_by_id(const std::string &name, const std::string &countersName, const std::string &lablesName, const DataplaneMetricsCountersLablesJsonObject &value);
  void create_dynmonitor_dataplane_metrics_counters_lables_list_by_id(const std::string &name, const std::string &countersName, const std::vector<DataplaneMetricsCountersLablesJsonObject> &value);
  void create_dynmonitor_dataplane_metrics_counters_list_by_id(const std::string &name, const std::vector<DataplaneMetricsCountersJsonObject> &value);
  void delete_dynmonitor_by_id(const std::string &name);
  void delete_dynmonitor_dataplane_by_id(const std::string &name);
  void delete_dynmonitor_dataplane_metrics_by_id(const std::string &name);
  void delete_dynmonitor_dataplane_metrics_counters_by_id(const std::string &name, const std::string &countersName);
  void delete_dynmonitor_dataplane_metrics_counters_lables_by_id(const std::string &name, const std::string &countersName, const std::string &lablesName);
  void delete_dynmonitor_dataplane_metrics_counters_lables_list_by_id(const std::string &name, const std::string &countersName);
  void delete_dynmonitor_dataplane_metrics_counters_list_by_id(const std::string &name);
  DynmonitorJsonObject read_dynmonitor_by_id(const std::string &name);
  DataplaneJsonObject read_dynmonitor_dataplane_by_id(const std::string &name);
  std::string read_dynmonitor_dataplane_code_by_id(const std::string &name);
  DataplaneMetricsJsonObject read_dynmonitor_dataplane_metrics_by_id(const std::string &name);
  DataplaneMetricsCountersJsonObject read_dynmonitor_dataplane_metrics_counters_by_id(const std::string &name, const std::string &countersName);
  DataplaneMetricsCountersLablesJsonObject read_dynmonitor_dataplane_metrics_counters_lables_by_id(const std::string &name, const std::string &countersName, const std::string &lablesName);
  std::vector<DataplaneMetricsCountersLablesJsonObject> read_dynmonitor_dataplane_metrics_counters_lables_list_by_id(const std::string &name, const std::string &countersName);
  std::vector<DataplaneMetricsCountersJsonObject> read_dynmonitor_dataplane_metrics_counters_list_by_id(const std::string &name);
  uint64_t read_dynmonitor_dataplane_metrics_counters_min_entries_by_id(const std::string &name, const std::string &countersName);
  std::string read_dynmonitor_dataplane_metrics_counters_table_name_by_id(const std::string &name, const std::string &countersName);
  std::string read_dynmonitor_dataplane_metrics_counters_table_type_by_id(const std::string &name, const std::string &countersName);
  std::string read_dynmonitor_dataplane_name_by_id(const std::string &name);
  std::vector<DynmonitorJsonObject> read_dynmonitor_list_by_id();
  MetricsJsonObject read_dynmonitor_metrics_by_id(const std::string &name);
  MetricsEntryJsonObject read_dynmonitor_metrics_entry_by_id(const std::string &name, const std::string &entryName);
  MetricsEntryLablesJsonObject read_dynmonitor_metrics_entry_lables_by_id(const std::string &name, const std::string &entryName, const std::string &lablesName);
  std::vector<MetricsEntryLablesJsonObject> read_dynmonitor_metrics_entry_lables_list_by_id(const std::string &name, const std::string &entryName);
  std::string read_dynmonitor_metrics_entry_lables_value_by_id(const std::string &name, const std::string &entryName, const std::string &lablesName);
  std::vector<MetricsEntryJsonObject> read_dynmonitor_metrics_entry_list_by_id(const std::string &name);
  int64_t read_dynmonitor_metrics_entry_timestamp_by_id(const std::string &name, const std::string &entryName);
  double read_dynmonitor_metrics_entry_value_by_id(const std::string &name, const std::string &entryName);
  void replace_dynmonitor_by_id(const std::string &name, const DynmonitorJsonObject &value);
  void replace_dynmonitor_dataplane_by_id(const std::string &name, const DataplaneJsonObject &value);
  void replace_dynmonitor_dataplane_metrics_by_id(const std::string &name, const DataplaneMetricsJsonObject &value);
  void replace_dynmonitor_dataplane_metrics_counters_by_id(const std::string &name, const std::string &countersName, const DataplaneMetricsCountersJsonObject &value);
  void replace_dynmonitor_dataplane_metrics_counters_lables_by_id(const std::string &name, const std::string &countersName, const std::string &lablesName, const DataplaneMetricsCountersLablesJsonObject &value);
  void replace_dynmonitor_dataplane_metrics_counters_lables_list_by_id(const std::string &name, const std::string &countersName, const std::vector<DataplaneMetricsCountersLablesJsonObject> &value);
  void replace_dynmonitor_dataplane_metrics_counters_list_by_id(const std::string &name, const std::vector<DataplaneMetricsCountersJsonObject> &value);
  void update_dynmonitor_by_id(const std::string &name, const DynmonitorJsonObject &value);
  void update_dynmonitor_dataplane_by_id(const std::string &name, const DataplaneJsonObject &value);
  void update_dynmonitor_dataplane_code_by_id(const std::string &name, const std::string &value);
  void update_dynmonitor_dataplane_metrics_by_id(const std::string &name, const DataplaneMetricsJsonObject &value);
  void update_dynmonitor_dataplane_metrics_counters_by_id(const std::string &name, const std::string &countersName, const DataplaneMetricsCountersJsonObject &value);
  void update_dynmonitor_dataplane_metrics_counters_lables_by_id(const std::string &name, const std::string &countersName, const std::string &lablesName, const DataplaneMetricsCountersLablesJsonObject &value);
  void update_dynmonitor_dataplane_metrics_counters_lables_list_by_id(const std::string &name, const std::string &countersName, const std::vector<DataplaneMetricsCountersLablesJsonObject> &value);
  void update_dynmonitor_dataplane_metrics_counters_list_by_id(const std::string &name, const std::vector<DataplaneMetricsCountersJsonObject> &value);
  void update_dynmonitor_dataplane_metrics_counters_min_entries_by_id(const std::string &name, const std::string &countersName, const uint64_t &value);
  void update_dynmonitor_dataplane_metrics_counters_table_name_by_id(const std::string &name, const std::string &countersName, const std::string &value);
  void update_dynmonitor_dataplane_metrics_counters_table_type_by_id(const std::string &name, const std::string &countersName, const std::string &value);
  void update_dynmonitor_dataplane_name_by_id(const std::string &name, const std::string &value);
  void update_dynmonitor_list_by_id(const std::vector<DynmonitorJsonObject> &value);

  /* help related */
  std::vector<nlohmann::fifo_map<std::string, std::string>> read_dynmonitor_dataplane_metrics_counters_lables_list_by_id_get_list(const std::string &name, const std::string &countersName);
  std::vector<nlohmann::fifo_map<std::string, std::string>> read_dynmonitor_dataplane_metrics_counters_list_by_id_get_list(const std::string &name);
  std::vector<nlohmann::fifo_map<std::string, std::string>> read_dynmonitor_list_by_id_get_list();
  std::vector<nlohmann::fifo_map<std::string, std::string>> read_dynmonitor_metrics_entry_lables_list_by_id_get_list(const std::string &name, const std::string &entryName);
  std::vector<nlohmann::fifo_map<std::string, std::string>> read_dynmonitor_metrics_entry_list_by_id_get_list(const std::string &name);

}
}
}
}

