/**
* dynmonitor API generated from dynmonitor.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


// TODO: Modify these methods with your own implementation


#include "DataplaneMetricsCountersLables.h"
#include "Dynmonitor.h"


DataplaneMetricsCountersLables::DataplaneMetricsCountersLables(DataplaneMetricsCounters &parent, const DataplaneMetricsCountersLablesJsonObject &conf)
    : DataplaneMetricsCountersLablesBase(parent) {
}

DataplaneMetricsCountersLables::~DataplaneMetricsCountersLables() {}

std::string DataplaneMetricsCountersLables::getName() {
  throw std::runtime_error("DataplaneMetricsCountersLables::getName: Method not implemented");
}


