/**
* dynmonitor API generated from dynmonitor.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


// TODO: Modify these methods with your own implementation


#include "MetricsEntryLables.h"
#include "Dynmonitor.h"


MetricsEntryLables::MetricsEntryLables(MetricsEntry &parent, const MetricsEntryLablesJsonObject &conf)
    : MetricsEntryLablesBase(parent) {
  if (conf.valueIsSet()) {
    setValue(conf.getValue());
  }

}

MetricsEntryLables::~MetricsEntryLables() {}

std::string MetricsEntryLables::getName() {
  throw std::runtime_error("MetricsEntryLables::getName: Method not implemented");
}

std::string MetricsEntryLables::getValue() {
  throw std::runtime_error("MetricsEntryLables::getValue: Method not implemented");
}

void MetricsEntryLables::setValue(const std::string &value) {
  throw std::runtime_error("MetricsEntryLables::setValue: Method not implemented");
}


