/**
* dynmonitor API generated from dynmonitor.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


#pragma once


#include "../base/MetricsEntryLablesBase.h"


class MetricsEntry;

using namespace polycube::service::model;

class MetricsEntryLables : public MetricsEntryLablesBase {
 public:
  MetricsEntryLables(MetricsEntry &parent, const MetricsEntryLablesJsonObject &conf);
  virtual ~MetricsEntryLables();

  /// <summary>
  /// LableName
  /// </summary>
  std::string getName() override;

  /// <summary>
  /// Lable value
  /// </summary>
  std::string getValue() override;
  void setValue(const std::string &value) override;
};
