/**
* dynmonitor API generated from dynmonitor.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* DataplaneMetricsCountersLablesJsonObject.h
*
*
*/

#pragma once


#include "JsonObjectBase.h"


namespace polycube {
namespace service {
namespace model {


/// <summary>
///
/// </summary>
class  DataplaneMetricsCountersLablesJsonObject : public JsonObjectBase {
public:
  DataplaneMetricsCountersLablesJsonObject();
  DataplaneMetricsCountersLablesJsonObject(const nlohmann::json &json);
  ~DataplaneMetricsCountersLablesJsonObject() final = default;
  nlohmann::json toJson() const final;


  /// <summary>
  /// LableName
  /// </summary>
  std::string getName() const;
  void setName(std::string value);
  bool nameIsSet() const;

private:
  std::string m_name;
  bool m_nameIsSet;
};

}
}
}

