/**
* dynmonitor API generated from dynmonitor.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* DataplaneMetricsJsonObject.h
*
*
*/

#pragma once


#include "JsonObjectBase.h"

#include "DataplaneMetricsCountersJsonObject.h"
#include <vector>

namespace polycube {
namespace service {
namespace model {


/// <summary>
///
/// </summary>
class  DataplaneMetricsJsonObject : public JsonObjectBase {
public:
  DataplaneMetricsJsonObject();
  DataplaneMetricsJsonObject(const nlohmann::json &json);
  ~DataplaneMetricsJsonObject() final = default;
  nlohmann::json toJson() const final;


  /// <summary>
  /// The list of exported coutners
  /// </summary>
  const std::vector<DataplaneMetricsCountersJsonObject>& getCounters() const;
  void addDataplaneMetricsCounters(DataplaneMetricsCountersJsonObject value);
  bool countersIsSet() const;
  void unsetCounters();

private:
  std::vector<DataplaneMetricsCountersJsonObject> m_counters;
  bool m_countersIsSet;
};

}
}
}

