/**
* dynmonitor API generated from dynmonitor.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */



#include "DynmonitorJsonObject.h"
#include <regex>

namespace polycube {
namespace service {
namespace model {

DynmonitorJsonObject::DynmonitorJsonObject() {
  m_nameIsSet = false;
  m_dataplaneIsSet = false;
  m_metricsIsSet = false;
}

DynmonitorJsonObject::DynmonitorJsonObject(const nlohmann::json &val) :
  JsonObjectBase(val) {
  m_nameIsSet = false;
  m_dataplaneIsSet = false;
  m_metricsIsSet = false;


  if (val.count("name")) {
    setName(val.at("name").get<std::string>());
  }

  if (val.count("dataplane")) {
    if (!val["dataplane"].is_null()) {
      DataplaneJsonObject newItem { val["dataplane"] };
      setDataplane(newItem);
    }
  }

  if (val.count("metrics")) {
    if (!val["metrics"].is_null()) {
      MetricsJsonObject newItem { val["metrics"] };
      setMetrics(newItem);
    }
  }
}

nlohmann::json DynmonitorJsonObject::toJson() const {
  nlohmann::json val = nlohmann::json::object();
  if (!getBase().is_null()) {
    val.update(getBase());
  }

  if (m_nameIsSet) {
    val["name"] = m_name;
  }

  if (m_dataplaneIsSet) {
    val["dataplane"] = JsonObjectBase::toJson(m_dataplane);
  }

  if (m_metricsIsSet) {
    val["metrics"] = JsonObjectBase::toJson(m_metrics);
  }

  return val;
}

std::string DynmonitorJsonObject::getName() const {
  return m_name;
}

void DynmonitorJsonObject::setName(std::string value) {
  m_name = value;
  m_nameIsSet = true;
}

bool DynmonitorJsonObject::nameIsSet() const {
  return m_nameIsSet;
}



DataplaneJsonObject DynmonitorJsonObject::getDataplane() const {
  return m_dataplane;
}

void DynmonitorJsonObject::setDataplane(DataplaneJsonObject value) {
  m_dataplane = value;
  m_dataplaneIsSet = true;
}

bool DynmonitorJsonObject::dataplaneIsSet() const {
  return m_dataplaneIsSet;
}

void DynmonitorJsonObject::unsetDataplane() {
  m_dataplaneIsSet = false;
}

MetricsJsonObject DynmonitorJsonObject::getMetrics() const {
  return m_metrics;
}

void DynmonitorJsonObject::setMetrics(MetricsJsonObject value) {
  m_metrics = value;
  m_metricsIsSet = true;
}

bool DynmonitorJsonObject::metricsIsSet() const {
  return m_metricsIsSet;
}

void DynmonitorJsonObject::unsetMetrics() {
  m_metricsIsSet = false;
}


}
}
}

