/**
* dynmonitor API generated from dynmonitor.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* MetricsJsonObject.h
*
*
*/

#pragma once


#include "JsonObjectBase.h"

#include "MetricsEntryJsonObject.h"
#include <vector>

namespace polycube {
namespace service {
namespace model {


/// <summary>
///
/// </summary>
class  MetricsJsonObject : public JsonObjectBase {
public:
  MetricsJsonObject();
  MetricsJsonObject(const nlohmann::json &json);
  ~MetricsJsonObject() final = default;
  nlohmann::json toJson() const final;


  /// <summary>
  ///
  /// </summary>
  const std::vector<MetricsEntryJsonObject>& getEntry() const;
  void addMetricsEntry(MetricsEntryJsonObject value);
  bool entryIsSet() const;
  void unsetEntry();

private:
  std::vector<MetricsEntryJsonObject> m_entry;
  bool m_entryIsSet;
};

}
}
}

