/**
* dynmonitor API generated from dynmonitor.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */



#include "MetricsEntryLablesJsonObject.h"
#include <regex>

namespace polycube {
namespace service {
namespace model {

MetricsEntryLablesJsonObject::MetricsEntryLablesJsonObject() {
  m_nameIsSet = false;
  m_valueIsSet = false;
}

MetricsEntryLablesJsonObject::MetricsEntryLablesJsonObject(const nlohmann::json &val) :
  JsonObjectBase(val) {
  m_nameIsSet = false;
  m_valueIsSet = false;


  if (val.count("name")) {
    setName(val.at("name").get<std::string>());
  }

  if (val.count("value")) {
    setValue(val.at("value").get<std::string>());
  }
}

nlohmann::json MetricsEntryLablesJsonObject::toJson() const {
  nlohmann::json val = nlohmann::json::object();
  if (!getBase().is_null()) {
    val.update(getBase());
  }

  if (m_nameIsSet) {
    val["name"] = m_name;
  }

  if (m_valueIsSet) {
    val["value"] = m_value;
  }

  return val;
}

std::string MetricsEntryLablesJsonObject::getName() const {
  return m_name;
}

void MetricsEntryLablesJsonObject::setName(std::string value) {
  m_name = value;
  m_nameIsSet = true;
}

bool MetricsEntryLablesJsonObject::nameIsSet() const {
  return m_nameIsSet;
}



std::string MetricsEntryLablesJsonObject::getValue() const {
  return m_value;
}

void MetricsEntryLablesJsonObject::setValue(std::string value) {
  m_value = value;
  m_valueIsSet = true;
}

bool MetricsEntryLablesJsonObject::valueIsSet() const {
  return m_valueIsSet;
}

void MetricsEntryLablesJsonObject::unsetValue() {
  m_valueIsSet = false;
}


}
}
}

