/**
* dynmonitor API generated from dynmonitor.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */



#include "MetricsJsonObject.h"
#include <regex>

namespace polycube {
namespace service {
namespace model {

MetricsJsonObject::MetricsJsonObject() {
  m_entryIsSet = false;
}

MetricsJsonObject::MetricsJsonObject(const nlohmann::json &val) :
  JsonObjectBase(val) {
  m_entryIsSet = false;


  if (val.count("entry")) {
    for (auto& item : val["entry"]) {
      MetricsEntryJsonObject newItem{ item };
      m_entry.push_back(newItem);
    }

    m_entryIsSet = true;
  }
}

nlohmann::json MetricsJsonObject::toJson() const {
  nlohmann::json val = nlohmann::json::object();
  if (!getBase().is_null()) {
    val.update(getBase());
  }

  {
    nlohmann::json jsonArray;
    for (auto& item : m_entry) {
      jsonArray.push_back(JsonObjectBase::toJson(item));
    }

    if (jsonArray.size() > 0) {
      val["entry"] = jsonArray;
    }
  }

  return val;
}

const std::vector<MetricsEntryJsonObject>& MetricsJsonObject::getEntry() const{
  return m_entry;
}

void MetricsJsonObject::addMetricsEntry(MetricsEntryJsonObject value) {
  m_entry.push_back(value);
  m_entryIsSet = true;
}


bool MetricsJsonObject::entryIsSet() const {
  return m_entryIsSet;
}

void MetricsJsonObject::unsetEntry() {
  m_entryIsSet = false;
}


}
}
}

