/**
* dynmonitor API generated from dynmonitor.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* MetricsEntryLablesJsonObject.h
*
*
*/

#pragma once


#include "JsonObjectBase.h"


namespace polycube {
namespace service {
namespace model {


/// <summary>
///
/// </summary>
class  MetricsEntryLablesJsonObject : public JsonObjectBase {
public:
  MetricsEntryLablesJsonObject();
  MetricsEntryLablesJsonObject(const nlohmann::json &json);
  ~MetricsEntryLablesJsonObject() final = default;
  nlohmann::json toJson() const final;


  /// <summary>
  /// LableName
  /// </summary>
  std::string getName() const;
  void setName(std::string value);
  bool nameIsSet() const;

  /// <summary>
  /// Lable value
  /// </summary>
  std::string getValue() const;
  void setValue(std::string value);
  bool valueIsSet() const;
  void unsetValue();

private:
  std::string m_name;
  bool m_nameIsSet;
  std::string m_value;
  bool m_valueIsSet;
};

}
}
}

