/**
* dynmonitor API generated from dynmonitor.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */


#include "DataplaneMetricsCountersLablesBase.h"
#include "../Dynmonitor.h"


DataplaneMetricsCountersLablesBase::DataplaneMetricsCountersLablesBase(DataplaneMetricsCounters &parent)
    : parent_(parent) {}

DataplaneMetricsCountersLablesBase::~DataplaneMetricsCountersLablesBase() {}

void DataplaneMetricsCountersLablesBase::update(const DataplaneMetricsCountersLablesJsonObject &conf) {

}

DataplaneMetricsCountersLablesJsonObject DataplaneMetricsCountersLablesBase::toJsonObject() {
  DataplaneMetricsCountersLablesJsonObject conf;

  conf.setName(getName());

  return conf;
}

std::shared_ptr<spdlog::logger> DataplaneMetricsCountersLablesBase::logger() {
  return parent_.logger();
}

