/**
* dynmonitor API generated from dynmonitor.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* DataplaneMetricsCountersLablesBase.h
*
*
*/

#pragma once

#include "../serializer/DataplaneMetricsCountersLablesJsonObject.h"






#include <spdlog/spdlog.h>

using namespace polycube::service::model;

class DataplaneMetricsCounters;

class DataplaneMetricsCountersLablesBase {
 public:
  
  DataplaneMetricsCountersLablesBase(DataplaneMetricsCounters &parent);
  
  virtual ~DataplaneMetricsCountersLablesBase();
  virtual void update(const DataplaneMetricsCountersLablesJsonObject &conf);
  virtual DataplaneMetricsCountersLablesJsonObject toJsonObject();

  /// <summary>
  /// LableName
  /// </summary>
  virtual std::string getName() = 0;

  std::shared_ptr<spdlog::logger> logger();
 protected:
  DataplaneMetricsCounters &parent_;
};
