/**
* dynmonitor API generated from dynmonitor.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* MetricsEntryLablesBase.h
*
*
*/

#pragma once

#include "../serializer/MetricsEntryLablesJsonObject.h"






#include <spdlog/spdlog.h>

using namespace polycube::service::model;

class MetricsEntry;

class MetricsEntryLablesBase {
 public:
  
  MetricsEntryLablesBase(MetricsEntry &parent);
  
  virtual ~MetricsEntryLablesBase();
  virtual void update(const MetricsEntryLablesJsonObject &conf);
  virtual MetricsEntryLablesJsonObject toJsonObject();

  /// <summary>
  /// LableName
  /// </summary>
  virtual std::string getName() = 0;

  /// <summary>
  /// Lable value
  /// </summary>
  virtual std::string getValue() = 0;
  virtual void setValue(const std::string &value) = 0;

  std::shared_ptr<spdlog::logger> logger();
 protected:
  MetricsEntry &parent_;
};
