/**
* dynmonitor API generated from dynmonitor.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */


#include "MetricsEntryLablesBase.h"
#include "../Dynmonitor.h"


MetricsEntryLablesBase::MetricsEntryLablesBase(MetricsEntry &parent)
    : parent_(parent) {}

MetricsEntryLablesBase::~MetricsEntryLablesBase() {}

void MetricsEntryLablesBase::update(const MetricsEntryLablesJsonObject &conf) {

  if (conf.valueIsSet()) {
    setValue(conf.getValue());
  }
}

MetricsEntryLablesJsonObject MetricsEntryLablesBase::toJsonObject() {
  MetricsEntryLablesJsonObject conf;

  conf.setName(getName());
  conf.setValue(getValue());

  return conf;
}

std::shared_ptr<spdlog::logger> MetricsEntryLablesBase::logger() {
  return parent_.logger();
}

