/**
* dynmonitor API generated from dynmonitor.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */


#include "MetricsEntryBase.h"
#include "../Dynmonitor.h"


MetricsEntryBase::MetricsEntryBase(Metrics &parent)
    : parent_(parent) {}

MetricsEntryBase::~MetricsEntryBase() {}

void MetricsEntryBase::update(const MetricsEntryJsonObject &conf) {

  if (conf.lablesIsSet()) {
    for (auto &i : conf.getLables()) {
      auto name = i.getName();
      auto m = getLables(name);
      m->update(i);
    }
  }
  if (conf.valueIsSet()) {
    setValue(conf.getValue());
  }
  if (conf.timestampIsSet()) {
    setTimestamp(conf.getTimestamp());
  }
}

MetricsEntryJsonObject MetricsEntryBase::toJsonObject() {
  MetricsEntryJsonObject conf;

  conf.setName(getName());
  for(auto &i : getLablesList()) {
    conf.addMetricsEntryLables(i->toJsonObject());
  }
  conf.setValue(getValue());
  conf.setTimestamp(getTimestamp());

  return conf;
}
void MetricsEntryBase::addLablesList(const std::vector<MetricsEntryLablesJsonObject> &conf) {
  for (auto &i : conf) {
    std::string name_ = i.getName();
    addLables(name_, i);
  }
}

void MetricsEntryBase::replaceLables(const std::string &name, const MetricsEntryLablesJsonObject &conf) {
  delLables(name);
  std::string name_ = conf.getName();
  addLables(name_, conf);
}

void MetricsEntryBase::delLablesList() {
  auto elements = getLablesList();
  for (auto &i : elements) {
    std::string name_ = i->getName();
    delLables(name_);
  }
}

std::shared_ptr<spdlog::logger> MetricsEntryBase::logger() {
  return parent_.logger();
}

